Repository high-five-ormi/Algoy-AI, pull requests merged in 2024-08, with the labels that each got.

#1 Docs: Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📚 documentation

#3 Docs: PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📚 documentation

#5 Feat: CI/CD 환경 구축
  .github/workflows/gradle.yml
Labels: ✨ feature

#6 Chore: CI/CD 배포하기
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/algoyai/AlgoyAiApplication.java
  src/main/java/com/example/algoyai/controller/DemoController.java
  src/main/java/com/example/algoyai/model/dto/DemoDto.java
  src/main/java/com/example/algoyai/model/entity/DemoEntity.java
  src/main/java/com/example/algoyai/repository/DemoRepository.java
  src/main/java/com/example/algoyai/service/DemoService.java
  src/main/resources/application.yml
  src/main/resources/static/DemoStyle.css
  src/main/resources/templates/DemoPage.html
  src/test/java/com/example/algoyai/AlgoyAiApplicationTests.java
Labels: 👷‍♂️ chore

#12 Documentation: gitignore 수정
  .gitignore
Labels: 📚 documentation

#14 Chore: build.gradle에 websocket과 redis 추가
  build.gradle
Labels: 👷‍♂️ chore

#16 Feature: 채팅 구현
  src/main/java/com/example/algoyai/config/MongoConfig.java
  src/main/java/com/example/algoyai/config/RedisConfig.java
  src/main/java/com/example/algoyai/config/WebSocketConfig.java
  src/main/java/com/example/algoyai/controller/ChatController.java
  src/main/java/com/example/algoyai/controller/DemoController.java
  src/main/java/com/example/algoyai/controller/WebSocketController.java
  src/main/java/com/example/algoyai/model/dto/DemoDto.java
  src/main/java/com/example/algoyai/model/entity/ChatMessage.java
  src/main/java/com/example/algoyai/model/entity/DemoEntity.java
  src/main/java/com/example/algoyai/repository/ChatMessageRepository.java
  src/main/java/com/example/algoyai/repository/DemoRepository.java
  src/main/java/com/example/algoyai/service/ChatService.java
  src/main/java/com/example/algoyai/service/DemoService.java
  src/main/java/com/example/algoyai/service/RedisSubscriber.java
  src/main/resources/application.yml
  src/test/java/com/example/algoyai/AlgoyAiApplicationTests.java
Labels: ✨ feature

#18 Design: 채팅 기능 테스트용 뷰 작성
  src/main/resources/static/DemoStyle.css
  src/main/resources/static/chat.css
  src/main/resources/templates/DemoPage.html
  src/main/resources/templates/chat.html
Labels: 🎨 design

#27 Feat: nginx test
  src/main/java/com/example/algoyai/controller/ChatController.java
  src/main/java/com/example/algoyai/controller/WebSocketController.java
Labels: ✨ feature

#30 Feat: ai pid 생성
  .github/workflows/gradle.yml
Labels: :package: deploy

#32 Feat: ngnix bug fix
  src/main/resources/application.yml
Labels: 🐞 bug

#34 Documentation: 프로젝트 초기화
  src/main/java/com/example/algoyai/config/DemoConfig.java
  src/main/java/com/example/algoyai/config/MongoConfig.java
  src/main/java/com/example/algoyai/config/RedisConfig.java
  src/main/java/com/example/algoyai/config/WebSocketConfig.java
  src/main/java/com/example/algoyai/controller/ChatController.java
  src/main/java/com/example/algoyai/controller/DemoController.java
  src/main/java/com/example/algoyai/controller/WebSocketController.java
  src/main/java/com/example/algoyai/model/dto/DemoDto.java
  src/main/java/com/example/algoyai/model/entity/ChatMessage.java
  src/main/java/com/example/algoyai/model/entity/DemoEntity.java
  src/main/java/com/example/algoyai/repository/ChatMessageRepository.java
  src/main/java/com/example/algoyai/repository/DemoRepository.java
  src/main/java/com/example/algoyai/service/ChatService.java
  src/main/java/com/example/algoyai/service/DemoService.java
  src/main/java/com/example/algoyai/service/RedisSubscriber.java
  src/main/java/com/example/algoyai/util/DemoUtil.java
  src/main/resources/static/chat.css
  src/main/resources/static/demo-style.css
  src/main/resources/templates/chat.html
  src/main/resources/templates/demo-page.html
Labels: 📚 documentation

#35 Feat: Nginx test
  src/main/java/com/example/algoyai/controller/DemoController.java
Labels: 🐞 bug

#36 Feat: Controller 변경
  src/main/java/com/example/algoyai/controller/DemoController.java
Labels: 🐞 bug

#37 Feat: Nginx 테스트중
  src/main/java/com/example/algoyai/controller/DemoController.java
Labels: 🐞 bug

#39 Chore: Redis 관련 종속성 및 설정 삭제
  build.gradle
  src/main/resources/application.yml
Labels: 👷‍♂️ chore

#46 Feature: Web Socket을 이용한 AI 기능 확인용 채팅 구현
  src/main/java/com/example/algoyai/config/DemoConfig.java
  src/main/java/com/example/algoyai/config/WebSocketConfig.java
  src/main/java/com/example/algoyai/controller/ChatController.java
  src/main/java/com/example/algoyai/controller/DemoController.java
  src/main/java/com/example/algoyai/controller/ViewController.java
  src/main/java/com/example/algoyai/model/dto/ChatMessageDto.java
  src/main/java/com/example/algoyai/model/dto/DemoDto.java
  src/main/java/com/example/algoyai/model/entity/ChatMessage.java
  src/main/java/com/example/algoyai/model/entity/DemoEntity.java
  src/main/java/com/example/algoyai/repository/ChatMessageRepository.java
  src/main/java/com/example/algoyai/repository/DemoRepository.java
  src/main/java/com/example/algoyai/service/ChatMessageService.java
  src/main/java/com/example/algoyai/service/DemoService.java
  src/main/java/com/example/algoyai/util/ChatDtoConvert.java
  src/main/java/com/example/algoyai/util/DemoUtil.java
  src/main/resources/static/css/style.css
  src/main/resources/static/demo-style.css
  src/main/resources/static/js/app.js
  src/main/resources/templates/chat.html
  src/main/resources/templates/demo-page.html
Labels: 🎨 design, ✨ feature, ⚒️ refactor

#48 Feat: css 경로수정
  src/main/resources/templates/chat.html
Labels: 🐞 bug

#49 Feat: 경로 문제 해결
  src/main/resources/templates/chat.html
Labels: 🐞 bug

#51 Feat: Nginx 경로 버그
  src/main/resources/templates/chat.html
Labels: 🐞 bug

#52 Feat: Nginx css 경로 찾기
  src/main/resources/templates/chat.html
Labels: 🐞 bug

#53 Feat: 경로 재수정
  src/main/resources/templates/chat.html
Labels: 🐞 bug

#54 Feature: path 고치기
  src/main/resources/templates/chat.html
Labels: 🐞 bug

#57 Chore: websocket 관련 종속성 제거 및 reactive web 종속성 추가
  build.gradle
Labels: 👷‍♂️ chore

#58 Feature: 앨런 AI와 연동하여 챗봇 구현
  src/main/java/com/example/algoyai/AlgoyAiApplication.java
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/java/com/example/algoyai/config/WebSocketConfig.java
  src/main/java/com/example/algoyai/controller/ChatController.java
  src/main/java/com/example/algoyai/controller/ViewController.java
  src/main/java/com/example/algoyai/model/dto/ChatMessageDto.java
  src/main/java/com/example/algoyai/model/entity/ChatMessage.java
  src/main/java/com/example/algoyai/repository/ChatMessageRepository.java
  src/main/java/com/example/algoyai/service/ChatMessageService.java
  src/main/java/com/example/algoyai/service/ChatService.java
  src/main/java/com/example/algoyai/util/ChatDtoConvert.java
  src/main/java/com/example/algoyai/util/ChatMessageMapper.java
  src/main/java/com/example/algoyai/util/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/static/css/style.css
  src/main/resources/static/js/app.js
  src/main/resources/templates/chat.html
  src/main/resources/templates/index.html
Labels: 📚 documentation, ✨ feature

#60 Bug: URL /ai/**를 통하도록 수정
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/java/com/example/algoyai/controller/ChatController.java
  src/main/java/com/example/algoyai/controller/ViewController.java
  src/main/resources/templates/index.html
Labels: 🐞 bug

#62 Bug: API 요청/응답을 받지 못하는 부분 수정
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/java/com/example/algoyai/util/GlobalExceptionHandler.java
Labels: 🐞 bug

#63 Bug: API 요청/응답을 받지 못하는 부분 수정
  src/main/java/com/example/algoyai/config/WebConfig.java
Labels: 🐞 bug

#64 Bug: API 요청/응답을 받지 못하는 부분 수정
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/java/com/example/algoyai/util/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: 🐞 bug

#66 Design: 챗봇 SSE 방식에서 마지막 응답만 받게하기 및 마크다운 양식 사용하기
  src/main/java/com/example/algoyai/service/ChatService.java
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/templates/index.html
Labels: 🎨 design, ✨ feature

#69 Feature: http로 앨런API 연동
  src/main/java/com/example/algoyai/controller/AllenController.java
  src/main/java/com/example/algoyai/repository/AllenRepository.java
  src/main/java/com/example/algoyai/service/AllenApiService.java
  src/main/java/com/example/algoyai/service/AllenService.java
  src/main/java/com/example/algoyai/service/HttpURLConnectionEx.java
Labels: ✨ feature

#70 Bug: SSE 방식의 마지막 응답을 받아오는 부분 수정
  src/main/resources/static/img/bot_icon.png
  src/main/resources/static/img/send_icon.png
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/templates/index.html
Labels: 🐞 bug, 🎨 design
