Repository high-five-ormi/Algoy-AI, pull requests merged in 2024-09, with the labels that each got.

#73 Enhancement: XSS 공격 방지
  build.gradle
  src/main/java/com/example/algoyai/config/JacksonConfig.java
  src/main/java/com/example/algoyai/controller/ChatController.java
  src/main/java/com/example/algoyai/model/dto/ChatMessageDto.java
  src/main/java/com/example/algoyai/model/entity/ChatMessage.java
  src/main/java/com/example/algoyai/repository/ChatMessageRepository.java
  src/main/java/com/example/algoyai/service/ChatService.java
  src/main/java/com/example/algoyai/util/ChatMessageMapper.java
  src/main/java/com/example/algoyai/util/InputSanitizer.java
  src/main/resources/static/script.js
  src/main/resources/templates/index.html
Labels: 🐞 bug, 👷‍♂️ chore, 🎨 design, 💪 enhancement

#75 Bug: HTML이 여전히 적용되는 경우에 대한 문제 해결
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
Labels: 🐞 bug, 🎨 design

#78 Refactor: Web 쪽 레포지토리로 프론트 부분은 분리
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/java/com/example/algoyai/controller/ViewController.java
  src/main/java/com/example/algoyai/model/dto/ChatMessageDto.java
  src/main/resources/application.yml
  src/main/resources/static/img/bot_icon.png
  src/main/resources/static/img/send_icon.png
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/templates/index.html
Labels: ⚒️ refactor

#81 Feat: api 연동 및 db 저장 기능
  build.gradle
  src/main/java/com/example/algoyai/controller/AllenController.java
  src/main/java/com/example/algoyai/model/dto/QuizRecommendDto.java
  src/main/java/com/example/algoyai/model/entity/QuizRecommend.java
  src/main/java/com/example/algoyai/repository/AllenRepository.java
  src/main/java/com/example/algoyai/service/AllenApiService.java
  src/main/java/com/example/algoyai/service/AllenService.java
  src/main/resources/application.yml
Labels: ✨ feature

#83 Bug : 오타 수정
  src/main/java/com/example/algoyai/controller/AllenController.java
  src/main/java/com/example/algoyai/service/AllenApiService.java
Labels: 🐞 bug

#85 Chore: ci/cd workflows에 Web 서버 url 환경 변수 추가
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#86 Chore: application.yml에 Web 서버 url 환경 변수 추가
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/resources/application.yml
Labels: 👷‍♂️ chore

#88 Documentation: 챗봇 관련 코드 주석 처리
  src/main/java/com/example/algoyai/config/JacksonConfig.java
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/java/com/example/algoyai/controller/ChatController.java
  src/main/java/com/example/algoyai/model/dto/ChatMessageDto.java
  src/main/java/com/example/algoyai/model/entity/ChatMessage.java
  src/main/java/com/example/algoyai/repository/ChatMessageRepository.java
  src/main/java/com/example/algoyai/service/ChatService.java
  src/main/java/com/example/algoyai/util/ChatMessageMapper.java
  src/main/java/com/example/algoyai/util/GlobalExceptionHandler.java
  src/main/java/com/example/algoyai/util/InputSanitizer.java
Labels: 📚 documentation

#89 Bug: WEB_IP 환경 변수 추가 후 배포 문제 수정
  .github/workflows/gradle.yml
Labels: 🐞 bug

#91 Bug: WEB_IP 환경 변수 추가 후 배포 문제 수정
  .github/workflows/gradle.yml
Labels: 🐞 bug

#92 Bug: IP 환경 변수 추가
  .github/workflows/gradle.yml
Labels: 🐞 bug

#93 Bug: Bug: 챗봇 연결 안됨
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/resources/application.yml
Labels: 🐞 bug

#94 Bug: Bad Gateway 해결
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/resources/application.yml
Labels: 🐞 bug

#95 Bug: 챗봇 연결 안됨
  src/main/resources/application.yml
Labels: 🐞 bug

#96 Bug: 챗봇 연결 안됨
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/resources/application.yml
Labels: 🐞 bug

#97 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#98 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#99 Bug: 챗봇 연결 안됨
  src/main/java/com/example/algoyai/config/WebConfig.java
Labels: 🐞 bug

#100 Bug: 챗봇 연결 안됨(403에러)
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/resources/application.yml
Labels: 🐞 bug

#101 Bug: 챗봇 연결 안됨(CORS 문제 추정)
  src/main/java/com/example/algoyai/config/WebConfig.java
Labels: 🐞 bug

#102 Documentation: api 키 리필(1일당 100개의 프롬프트)
  src/main/resources/application.yml
Labels: 📚 documentation

#103 Documentation: api 키 리필(1일당 100개의 프롬프트)
  src/main/resources/application.yml
Labels: 📚 documentation

#105 Feat: user의 100문제 기반으로 allen에게 문제 추천받는 기능
  src/main/java/com/example/algoyai/controller/AllenController.java
  src/main/java/com/example/algoyai/model/dto/SolvedACResponse.java
  src/main/java/com/example/algoyai/service/AllenApiService.java
  src/main/resources/application.yml
Labels: ✨ feature

#108 Refactor: 챗봇 파일명과 경로 리팩토링 및 환경변수 설정
  src/main/java/com/example/algoyai/config/WebConfig.java
  src/main/java/com/example/algoyai/controller/chatbot/ChatController.java
  src/main/java/com/example/algoyai/model/dto/chatbot/ChatMessageDto.java
  src/main/java/com/example/algoyai/model/entity/chatbot/ChatMessage.java
  src/main/java/com/example/algoyai/repository/AllenRepository.java
  src/main/java/com/example/algoyai/repository/chatbot/ChatMessageRepository.java
  src/main/java/com/example/algoyai/service/chatbot/ChatService.java
  src/main/java/com/example/algoyai/util/chatbot/ChatMessageMapper.java
  src/main/resources/application.yml
Labels: ⚒️ refactor

#109 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#111 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#112 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#113 Test: 챗봇 테스트 코드 작성하기
  build.gradle
  src/main/java/com/example/algoyai/service/chatbot/ChatService.java
  src/test/java/com/example/algoyai/controller/chatbot/ChatControllerTest.java
  src/test/java/com/example/algoyai/repository/chatbot/ChatMessageRepositoryTest.java
  src/test/java/com/example/algoyai/service/chatbot/ChatServiceTest.java
  src/test/resources/application.yml
Labels: 📚 documentation, 👷‍♂️ chore, ⚒️ refactor, ✅ test

#115 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 🐞 bug, 👷‍♂️ chore

#116 Bug:테스트 코드 추가 후 ci/cd 실패
  src/test/java/com/example/algoyai/repository/chatbot/ChatMessageRepositoryTest.java
  src/test/resources/application.yml
Labels: 🐞 bug

#117 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 🐞 bug, 👷‍♂️ chore

#118 Enhancement: 앨런에게 JSON으로 답변받기
  src/main/java/com/example/algoyai/controller/AllenController.java
  src/main/java/com/example/algoyai/service/AllenApiService.java
Labels: 💪 enhancement

#119 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 🐞 bug, 👷‍♂️ chore

#120 Bug: 테스트 코드 추가 후 ci/cd 실패
  src/test/java/com/example/algoyai/repository/chatbot/ChatMessageRepositoryTest.java
  src/test/resources/application.yml
Labels: 🐞 bug

#122 Bug:테스트 코드 추가 후 ci/cd 실패
  src/main/java/com/example/algoyai/model/entity/chatbot/ChatMessage.java
  src/test/java/com/example/algoyai/repository/chatbot/ChatMessageRepositoryTest.java
  src/test/resources/application.yml
Labels: 🐞 bug

#123 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 🐞 bug, 👷‍♂️ chore

#124 Refeactor: files 정리
  src/main/java/com/example/algoyai/controller/solvedac/AllenController.java
  src/main/java/com/example/algoyai/model/dto/solvedac/QuizRecommendDto.java
  src/main/java/com/example/algoyai/model/dto/solvedac/SolvedACResponse.java
  src/main/java/com/example/algoyai/model/entity/solvedac/QuizRecommend.java
  src/main/java/com/example/algoyai/repository/solvedac/AllenRepository.java
  src/main/java/com/example/algoyai/service/solvedac/AllenApiService.java
  src/main/java/com/example/algoyai/service/solvedac/AllenService.java
  src/main/java/com/example/algoyai/service/solvedac/HttpURLConnectionEx.java
Labels: ⚒️ refactor

#126 Enhancement: 5문제 json으로 추천받기
  src/main/java/com/example/algoyai/controller/solvedac/AllenController.java
  src/main/java/com/example/algoyai/model/dto/solvedac/SolvedACResponse.java
  src/main/java/com/example/algoyai/service/solvedac/AllenApiService.java
  src/main/resources/application-local.yml
Labels: 💪 enhancement

#128 Bug: 배포 test
  src/main/java/com/example/algoyai/controller/solvedac/AllenController.java
Labels: 🐞 bug

#130 Test: AlgoyAI의 통합 테스트 작성
  build.gradle
  src/test/java/com/example/algoyai/AlgoyAiApplicationTests.java
  src/test/resources/application.yml
Labels: 👷‍♂️ chore, ✅ test

#131 Documentation: 줄 정리(배포 확인용)
  src/main/java/com/example/algoyai/config/WebConfig.java
Labels: 📚 documentation

#132 Deploy: gradle.yml 수정
  .github/workflows/gradle.yml
Labels: :package: deploy

#133 Bug: ec2 t3에서 배포하기
  .github/workflows/gradle.yml
Labels: 🐞 bug

#134 Documentation: local yml 삭제
  src/main/resources/application-local.yml
Labels: 📚 documentation

#135 Documentation: MongoDB IP 변경
  src/main/resources/application.yml
Labels: 📚 documentation

#136 Documentation: MongoDB IP 변경
  src/main/resources/application.yml
Labels: 📚 documentation
